export type AuthUserProfileResponse = {
  userId: string;
  authId: string;
  email?: string | null;
  emailVerified?: boolean | null;
  lastLoginAt?: Date | null;
  phoneNumber?: string | null;
  provider?: string | null;
  providerId?: string | null;
  twoFactorEnabled?: boolean | null;
  userName?: string | null;
  name?: string | null;
  lastName?: string | null;
  bio?: string | null;
  avatarUrl?: string | null;
  role?: string | null;
  status?: string | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
};
